repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff-format

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.28.2
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.0
    hooks:
    - id: clang-format
      types_or: [c++, c]
      # exclude: <regex>

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.0.3
    hooks:
      - id: editorconfig-checker
        # exclude: <regex>
