#!/bin/bash

set -ex

# generated by
# code-insiders --list-extensions | xargs -L 1 echo code --install-extension

code --install-extension alefragnani.numbered-bookmarks
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension haskell.haskell
code --install-extension justusadam.language-haskell
code --install-extension llvm-vs-code-extensions.vscode-clangd
code --install-extension ms-vscode.cmake-tools
code --install-extension shopify.ruby-lsp
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension twxs.cmake
code --install-extension vadimcn.vscode-lldb
code --install-extension yzhang.markdown-all-in-one
